# Generated by Django 4.2.4 on 2023-11-29 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Region",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("region", models.CharField(max_length=200)),
                ("lat", models.TextField()),
                ("loc", models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name="Redion",
        ),
    ]
