# Generated by Django 4.2.4 on 2023-11-29 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0003_crime_delete_region"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuthGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, unique=True)),
            ],
            options={
                "db_table": "auth_group",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AuthGroupPermissions",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                "db_table": "auth_group_permissions",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AuthPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("codename", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "auth_permission",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AuthUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128)),
                ("last_login", models.DateTimeField(blank=True, null=True)),
                ("is_superuser", models.IntegerField()),
                ("username", models.CharField(max_length=150, unique=True)),
                ("first_name", models.CharField(max_length=150)),
                ("last_name", models.CharField(max_length=150)),
                ("email", models.CharField(max_length=254)),
                ("is_staff", models.IntegerField()),
                ("is_active", models.IntegerField()),
                ("date_joined", models.DateTimeField()),
            ],
            options={
                "db_table": "auth_user",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AuthUserGroups",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                "db_table": "auth_user_groups",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AuthUserUserPermissions",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                "db_table": "auth_user_user_permissions",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Clearance",
            fields=[
                (
                    "clearance",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        primary_key=True,
                        serialize=False,
                        to="data.crime",
                    ),
                ),
                ("district", models.CharField(db_column="District", max_length=30)),
                ("murder", models.IntegerField(db_column="Murder")),
                ("robbery", models.IntegerField(db_column="Robbery")),
                ("rape", models.IntegerField(db_column="Rape")),
                ("theft", models.IntegerField(db_column="Theft")),
                ("violence", models.IntegerField(db_column="Violence")),
            ],
            options={
                "db_table": "clearance",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="DataCrime",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("district", models.CharField(max_length=200)),
                ("murder", models.IntegerField()),
                ("theft", models.IntegerField()),
            ],
            options={
                "db_table": "data_crime",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="DjangoAdminLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action_time", models.DateTimeField()),
                ("object_id", models.TextField(blank=True, null=True)),
                ("object_repr", models.CharField(max_length=200)),
                ("action_flag", models.PositiveSmallIntegerField()),
                ("change_message", models.TextField()),
            ],
            options={
                "db_table": "django_admin_log",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="DjangoContentType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("app_label", models.CharField(max_length=100)),
                ("model", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "django_content_type",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="DjangoMigrations",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("app", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
                ("applied", models.DateTimeField()),
            ],
            options={
                "db_table": "django_migrations",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="DjangoSession",
            fields=[
                (
                    "session_key",
                    models.CharField(max_length=40, primary_key=True, serialize=False),
                ),
                ("session_data", models.TextField()),
                ("expire_date", models.DateTimeField()),
            ],
            options={
                "db_table": "django_session",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="DobongBylocation",
            fields=[
                ("location_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "location",
                    models.CharField(
                        blank=True, db_column="Location", max_length=350, null=True
                    ),
                ),
                (
                    "murder",
                    models.IntegerField(blank=True, db_column="Murder", null=True),
                ),
                (
                    "robbery",
                    models.IntegerField(blank=True, db_column="Robbery", null=True),
                ),
                ("rape", models.IntegerField(blank=True, db_column="Rape", null=True)),
                (
                    "theft",
                    models.IntegerField(blank=True, db_column="Theft", null=True),
                ),
                (
                    "violence",
                    models.IntegerField(blank=True, db_column="Violence", null=True),
                ),
            ],
            options={
                "db_table": "dobong_bylocation",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="DongdaemunBylocation",
            fields=[
                ("location_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "location",
                    models.CharField(
                        blank=True, db_column="Location", max_length=350, null=True
                    ),
                ),
                (
                    "murder",
                    models.IntegerField(blank=True, db_column="Murder", null=True),
                ),
                (
                    "robbery",
                    models.IntegerField(blank=True, db_column="Robbery", null=True),
                ),
                ("rape", models.IntegerField(blank=True, db_column="Rape", null=True)),
                (
                    "theft",
                    models.IntegerField(blank=True, db_column="Theft", null=True),
                ),
                (
                    "violence",
                    models.IntegerField(blank=True, db_column="Violence", null=True),
                ),
            ],
            options={
                "db_table": "dongdaemun_bylocation",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="DongjakBylocation",
            fields=[
                ("location_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "location",
                    models.CharField(
                        blank=True, db_column="Location", max_length=350, null=True
                    ),
                ),
                (
                    "murder",
                    models.IntegerField(blank=True, db_column="Murder", null=True),
                ),
                (
                    "robbery",
                    models.IntegerField(blank=True, db_column="Robbery", null=True),
                ),
                ("rape", models.IntegerField(blank=True, db_column="Rape", null=True)),
                (
                    "theft",
                    models.IntegerField(blank=True, db_column="Theft", null=True),
                ),
                (
                    "violence",
                    models.IntegerField(blank=True, db_column="Violence", null=True),
                ),
            ],
            options={
                "db_table": "dongjak_bylocation",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="EunpyeongBylocation",
            fields=[
                ("location_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "location",
                    models.CharField(
                        blank=True, db_column="Location", max_length=350, null=True
                    ),
                ),
                (
                    "murder",
                    models.IntegerField(blank=True, db_column="Murder", null=True),
                ),
                (
                    "robbery",
                    models.IntegerField(blank=True, db_column="Robbery", null=True),
                ),
                ("rape", models.IntegerField(blank=True, db_column="Rape", null=True)),
                (
                    "theft",
                    models.IntegerField(blank=True, db_column="Theft", null=True),
                ),
                (
                    "violence",
                    models.IntegerField(blank=True, db_column="Violence", null=True),
                ),
            ],
            options={
                "db_table": "eunpyeong_bylocation",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="GangbukBylocation",
            fields=[
                ("location_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "location",
                    models.CharField(
                        blank=True, db_column="Location", max_length=350, null=True
                    ),
                ),
                (
                    "murder",
                    models.IntegerField(blank=True, db_column="Murder", null=True),
                ),
                (
                    "robbery",
                    models.IntegerField(blank=True, db_column="Robbery", null=True),
                ),
                ("rape", models.IntegerField(blank=True, db_column="Rape", null=True)),
                (
                    "theft",
                    models.IntegerField(blank=True, db_column="Theft", null=True),
                ),
                (
                    "violence",
                    models.IntegerField(blank=True, db_column="Violence", null=True),
                ),
            ],
            options={
                "db_table": "gangbuk_bylocation",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="GangdongBylocation",
            fields=[
                ("location_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "location",
                    models.CharField(
                        blank=True, db_column="Location", max_length=350, null=True
                    ),
                ),
                (
                    "murder",
                    models.IntegerField(blank=True, db_column="Murder", null=True),
                ),
                (
                    "robbery",
                    models.IntegerField(blank=True, db_column="Robbery", null=True),
                ),
                ("rape", models.IntegerField(blank=True, db_column="Rape", null=True)),
                (
                    "theft",
                    models.IntegerField(blank=True, db_column="Theft", null=True),
                ),
                (
                    "violence",
                    models.IntegerField(blank=True, db_column="Violence", null=True),
                ),
            ],
            options={
                "db_table": "gangdong_bylocation",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="GangnamBylocation",
            fields=[
                ("location_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "location",
                    models.CharField(
                        blank=True, db_column="Location", max_length=350, null=True
                    ),
                ),
                (
                    "murder",
                    models.IntegerField(blank=True, db_column="Murder", null=True),
                ),
                (
                    "robbery",
                    models.IntegerField(blank=True, db_column="Robbery", null=True),
                ),
                ("rape", models.IntegerField(blank=True, db_column="Rape", null=True)),
                (
                    "theft",
                    models.IntegerField(blank=True, db_column="Theft", null=True),
                ),
                (
                    "violence",
                    models.IntegerField(blank=True, db_column="Violence", null=True),
                ),
            ],
            options={
                "db_table": "gangnam_bylocation",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="GangseoBylocation",
            fields=[
                ("location_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "location",
                    models.CharField(
                        blank=True, db_column="Location", max_length=350, null=True
                    ),
                ),
                (
                    "murder",
                    models.IntegerField(blank=True, db_column="Murder", null=True),
                ),
                (
                    "robbery",
                    models.IntegerField(blank=True, db_column="Robbery", null=True),
                ),
                ("rape", models.IntegerField(blank=True, db_column="Rape", null=True)),
                (
                    "theft",
                    models.IntegerField(blank=True, db_column="Theft", null=True),
                ),
                (
                    "violence",
                    models.IntegerField(blank=True, db_column="Violence", null=True),
                ),
            ],
            options={
                "db_table": "gangseo_bylocation",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="GeumcheonBylocation",
            fields=[
                ("location_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "location",
                    models.CharField(
                        blank=True, db_column="Location", max_length=350, null=True
                    ),
                ),
                (
                    "murder",
                    models.IntegerField(blank=True, db_column="Murder", null=True),
                ),
                (
                    "robbery",
                    models.IntegerField(blank=True, db_column="Robbery", null=True),
                ),
                ("rape", models.IntegerField(blank=True, db_column="Rape", null=True)),
                (
                    "theft",
                    models.IntegerField(blank=True, db_column="Theft", null=True),
                ),
                (
                    "violence",
                    models.IntegerField(blank=True, db_column="Violence", null=True),
                ),
            ],
            options={
                "db_table": "geumcheon_bylocation",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="GuroBylocation",
            fields=[
                ("location_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "location",
                    models.CharField(
                        blank=True, db_column="Location", max_length=350, null=True
                    ),
                ),
                (
                    "murder",
                    models.IntegerField(blank=True, db_column="Murder", null=True),
                ),
                (
                    "robbery",
                    models.IntegerField(blank=True, db_column="Robbery", null=True),
                ),
                ("rape", models.IntegerField(blank=True, db_column="Rape", null=True)),
                (
                    "theft",
                    models.IntegerField(blank=True, db_column="Theft", null=True),
                ),
                (
                    "violence",
                    models.IntegerField(blank=True, db_column="Violence", null=True),
                ),
            ],
            options={
                "db_table": "guro_bylocation",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="GwanakBylocation",
            fields=[
                ("location_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "location",
                    models.CharField(
                        blank=True, db_column="Location", max_length=350, null=True
                    ),
                ),
                (
                    "murder",
                    models.IntegerField(blank=True, db_column="Murder", null=True),
                ),
                (
                    "robbery",
                    models.IntegerField(blank=True, db_column="Robbery", null=True),
                ),
                ("rape", models.IntegerField(blank=True, db_column="Rape", null=True)),
                (
                    "theft",
                    models.IntegerField(blank=True, db_column="Theft", null=True),
                ),
                (
                    "violence",
                    models.IntegerField(blank=True, db_column="Violence", null=True),
                ),
            ],
            options={
                "db_table": "gwanak_bylocation",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="GwangjinBylocation",
            fields=[
                ("location_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "location",
                    models.CharField(
                        blank=True, db_column="Location", max_length=350, null=True
                    ),
                ),
                (
                    "murder",
                    models.IntegerField(blank=True, db_column="Murder", null=True),
                ),
                (
                    "robbery",
                    models.IntegerField(blank=True, db_column="Robbery", null=True),
                ),
                ("rape", models.IntegerField(blank=True, db_column="Rape", null=True)),
                (
                    "theft",
                    models.IntegerField(blank=True, db_column="Theft", null=True),
                ),
                (
                    "violence",
                    models.IntegerField(blank=True, db_column="Violence", null=True),
                ),
            ],
            options={
                "db_table": "gwangjin_bylocation",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="JongnoBylocation",
            fields=[
                ("location_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "location",
                    models.CharField(
                        blank=True, db_column="Location", max_length=350, null=True
                    ),
                ),
                (
                    "murder",
                    models.IntegerField(blank=True, db_column="Murder", null=True),
                ),
                (
                    "robbery",
                    models.IntegerField(blank=True, db_column="Robbery", null=True),
                ),
                ("rape", models.IntegerField(blank=True, db_column="Rape", null=True)),
                (
                    "theft",
                    models.IntegerField(blank=True, db_column="Theft", null=True),
                ),
                (
                    "violence",
                    models.IntegerField(blank=True, db_column="Violence", null=True),
                ),
            ],
            options={
                "db_table": "jongno_bylocation",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="JungguBylocation",
            fields=[
                ("location_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "location",
                    models.CharField(
                        blank=True, db_column="Location", max_length=350, null=True
                    ),
                ),
                (
                    "murder",
                    models.IntegerField(blank=True, db_column="Murder", null=True),
                ),
                (
                    "robbery",
                    models.IntegerField(blank=True, db_column="Robbery", null=True),
                ),
                ("rape", models.IntegerField(blank=True, db_column="Rape", null=True)),
                (
                    "theft",
                    models.IntegerField(blank=True, db_column="Theft", null=True),
                ),
                (
                    "violence",
                    models.IntegerField(blank=True, db_column="Violence", null=True),
                ),
            ],
            options={
                "db_table": "junggu_bylocation",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="JungnangBylocation",
            fields=[
                ("location_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "location",
                    models.CharField(
                        blank=True, db_column="Location", max_length=350, null=True
                    ),
                ),
                (
                    "murder",
                    models.IntegerField(blank=True, db_column="Murder", null=True),
                ),
                (
                    "robbery",
                    models.IntegerField(blank=True, db_column="Robbery", null=True),
                ),
                ("rape", models.IntegerField(blank=True, db_column="Rape", null=True)),
                (
                    "theft",
                    models.IntegerField(blank=True, db_column="Theft", null=True),
                ),
                (
                    "violence",
                    models.IntegerField(blank=True, db_column="Violence", null=True),
                ),
            ],
            options={
                "db_table": "jungnang_bylocation",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="MapoBylocation",
            fields=[
                ("location_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "location",
                    models.CharField(
                        blank=True, db_column="Location", max_length=350, null=True
                    ),
                ),
                (
                    "murder",
                    models.IntegerField(blank=True, db_column="Murder", null=True),
                ),
                (
                    "robbery",
                    models.IntegerField(blank=True, db_column="Robbery", null=True),
                ),
                ("rape", models.IntegerField(blank=True, db_column="Rape", null=True)),
                (
                    "theft",
                    models.IntegerField(blank=True, db_column="Theft", null=True),
                ),
                (
                    "violence",
                    models.IntegerField(blank=True, db_column="Violence", null=True),
                ),
            ],
            options={
                "db_table": "mapo_bylocation",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="NowonBylocation",
            fields=[
                ("location_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "location",
                    models.CharField(
                        blank=True, db_column="Location", max_length=350, null=True
                    ),
                ),
                (
                    "murder",
                    models.IntegerField(blank=True, db_column="Murder", null=True),
                ),
                (
                    "robbery",
                    models.IntegerField(blank=True, db_column="Robbery", null=True),
                ),
                ("rape", models.IntegerField(blank=True, db_column="Rape", null=True)),
                (
                    "theft",
                    models.IntegerField(blank=True, db_column="Theft", null=True),
                ),
                (
                    "violence",
                    models.IntegerField(blank=True, db_column="Violence", null=True),
                ),
            ],
            options={
                "db_table": "nowon_bylocation",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="PyboAnswer",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("content", models.TextField()),
                ("create_date", models.DateTimeField()),
            ],
            options={
                "db_table": "pybo_answer",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="PyboQuestion",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("subject", models.CharField(max_length=200)),
                ("content", models.TextField()),
                ("create_date", models.DateTimeField()),
            ],
            options={
                "db_table": "pybo_question",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="SeochoBylocation",
            fields=[
                ("location_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "location",
                    models.CharField(
                        blank=True, db_column="Location", max_length=350, null=True
                    ),
                ),
                (
                    "murder",
                    models.IntegerField(blank=True, db_column="Murder", null=True),
                ),
                (
                    "robbery",
                    models.IntegerField(blank=True, db_column="Robbery", null=True),
                ),
                ("rape", models.IntegerField(blank=True, db_column="Rape", null=True)),
                (
                    "theft",
                    models.IntegerField(blank=True, db_column="Theft", null=True),
                ),
                (
                    "violence",
                    models.IntegerField(blank=True, db_column="Violence", null=True),
                ),
            ],
            options={
                "db_table": "seocho_bylocation",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="SeodaemunBylocation",
            fields=[
                ("location_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "location",
                    models.CharField(
                        blank=True, db_column="Location", max_length=350, null=True
                    ),
                ),
                (
                    "murder",
                    models.IntegerField(blank=True, db_column="Murder", null=True),
                ),
                (
                    "robbery",
                    models.IntegerField(blank=True, db_column="Robbery", null=True),
                ),
                ("rape", models.IntegerField(blank=True, db_column="Rape", null=True)),
                (
                    "theft",
                    models.IntegerField(blank=True, db_column="Theft", null=True),
                ),
                (
                    "violence",
                    models.IntegerField(blank=True, db_column="Violence", null=True),
                ),
            ],
            options={
                "db_table": "seodaemun_bylocation",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="SeongbukBylocation",
            fields=[
                ("location_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "location",
                    models.CharField(
                        blank=True, db_column="Location", max_length=350, null=True
                    ),
                ),
                (
                    "murder",
                    models.IntegerField(blank=True, db_column="Murder", null=True),
                ),
                (
                    "robbery",
                    models.IntegerField(blank=True, db_column="Robbery", null=True),
                ),
                ("rape", models.IntegerField(blank=True, db_column="Rape", null=True)),
                (
                    "theft",
                    models.IntegerField(blank=True, db_column="Theft", null=True),
                ),
                (
                    "violence",
                    models.IntegerField(blank=True, db_column="Violence", null=True),
                ),
            ],
            options={
                "db_table": "seongbuk_bylocation",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="SeongdongBylocation",
            fields=[
                ("location_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "location",
                    models.CharField(
                        blank=True, db_column="Location", max_length=350, null=True
                    ),
                ),
                (
                    "murder",
                    models.IntegerField(blank=True, db_column="Murder", null=True),
                ),
                (
                    "robbery",
                    models.IntegerField(blank=True, db_column="Robbery", null=True),
                ),
                ("rape", models.IntegerField(blank=True, db_column="Rape", null=True)),
                (
                    "theft",
                    models.IntegerField(blank=True, db_column="Theft", null=True),
                ),
                (
                    "violence",
                    models.IntegerField(blank=True, db_column="Violence", null=True),
                ),
            ],
            options={
                "db_table": "seongdong_bylocation",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="SongpaBylocation",
            fields=[
                ("location_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "location",
                    models.CharField(
                        blank=True, db_column="Location", max_length=350, null=True
                    ),
                ),
                (
                    "murder",
                    models.IntegerField(blank=True, db_column="Murder", null=True),
                ),
                (
                    "robbery",
                    models.IntegerField(blank=True, db_column="Robbery", null=True),
                ),
                ("rape", models.IntegerField(blank=True, db_column="Rape", null=True)),
                (
                    "theft",
                    models.IntegerField(blank=True, db_column="Theft", null=True),
                ),
                (
                    "violence",
                    models.IntegerField(blank=True, db_column="Violence", null=True),
                ),
            ],
            options={
                "db_table": "songpa_bylocation",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="YangcheonBylocation",
            fields=[
                ("location_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "location",
                    models.CharField(
                        blank=True, db_column="Location", max_length=350, null=True
                    ),
                ),
                (
                    "murder",
                    models.IntegerField(blank=True, db_column="Murder", null=True),
                ),
                (
                    "robbery",
                    models.IntegerField(blank=True, db_column="Robbery", null=True),
                ),
                ("rape", models.IntegerField(blank=True, db_column="Rape", null=True)),
                (
                    "theft",
                    models.IntegerField(blank=True, db_column="Theft", null=True),
                ),
                (
                    "violence",
                    models.IntegerField(blank=True, db_column="Violence", null=True),
                ),
            ],
            options={
                "db_table": "yangcheon_bylocation",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="YongsanBylocation",
            fields=[
                ("location_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "location",
                    models.CharField(
                        blank=True, db_column="Location", max_length=350, null=True
                    ),
                ),
                (
                    "murder",
                    models.IntegerField(blank=True, db_column="Murder", null=True),
                ),
                (
                    "robbery",
                    models.IntegerField(blank=True, db_column="Robbery", null=True),
                ),
                ("rape", models.IntegerField(blank=True, db_column="Rape", null=True)),
                (
                    "theft",
                    models.IntegerField(blank=True, db_column="Theft", null=True),
                ),
                (
                    "violence",
                    models.IntegerField(blank=True, db_column="Violence", null=True),
                ),
            ],
            options={
                "db_table": "yongsan_bylocation",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="YeongdeungpoBylocation",
            fields=[
                ("location_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "location",
                    models.CharField(
                        blank=True, db_column="Location", max_length=350, null=True
                    ),
                ),
                (
                    "murder",
                    models.IntegerField(blank=True, db_column="Murder", null=True),
                ),
                (
                    "robbery",
                    models.IntegerField(blank=True, db_column="Robbery", null=True),
                ),
                ("rape", models.IntegerField(blank=True, db_column="Rape", null=True)),
                (
                    "theft",
                    models.IntegerField(blank=True, db_column="Theft", null=True),
                ),
            ],
        ),
        migrations.AlterModelOptions(
            name="crime",
            options={"managed": False},
        ),
    ]
