# Generated by Django 4.2.4 on 2023-11-29 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0004_authgroup_authgrouppermissions_authpermission_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="crime",
            table="crime",
        ),
    ]
