# Generated by Django 4.2.4 on 2023-11-29 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0005_alter_crime_table"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DataCrime",
        ),
        migrations.DeleteModel(
            name="PyboAnswer",
        ),
        migrations.DeleteModel(
            name="PyboQuestion",
        ),
    ]
