# Generated by Django 4.2.4 on 2023-11-29 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0006_delete_datacrime_delete_pyboanswer_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="yeongdeungpobylocation",
            options={"managed": False},
        ),
    ]
