# Generated by Django 4.2.4 on 2023-11-29 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0007_alter_yeongdeungpobylocation_options"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="yeongdeungpobylocation",
            table="yeongdeungpo_bylocation",
        ),
    ]
